# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4483d09805247cc1bd88060ef38b43afaf02d6c2636cfc716056b38a9f2e01ff677bda07dc23bfebbd4409cca10316d00651f902187983b6a70bcadc8822df1

test:
  secret_key_base: 55402313ceac586dda176387560232fddbdea13b3f44c4aeaaf4042982191c8f44309559e2aa4fc26a7c9bb5b287d3d47aeeddd58c08007df2787cc8e2078876

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
